#ifndef PALETTES_H
#define PALETTES_H

/* Arctic Sunrise by Neil Richards */
#define ARCTIC_SUNRISE_DAINTY_PEACH_R (0xFF)
#define ARCTIC_SUNRISE_DAINTY_PEACH_G (0xCC)
#define ARCTIC_SUNRISE_DAINTY_PEACH_B (0xBB)
#define ARCTIC_SUNRISE_WATER_MUSIC_R (0x6E)
#define ARCTIC_SUNRISE_WATER_MUSIC_G (0xB5)
#define ARCTIC_SUNRISE_WATER_MUSIC_B (0xC0)
#define ARCTIC_SUNRISE_AZURE_GREEN_BLUE_R (0x00)
#define ARCTIC_SUNRISE_AZURE_GREEN_BLUE_G (0x6C)
#define ARCTIC_SUNRISE_AZURE_GREEN_BLUE_B (0x84)
#define ARCTIC_SUNRISE_RARIFIED_AIR_R (0xE2)
#define ARCTIC_SUNRISE_RARIFIED_AIR_G (0xE8)
#define ARCTIC_SUNRISE_RARIFIED_AIR_B (0xE4)
#endif /* PALETTES_H */
